# Author: Hee Won Lee <knowpd@research.att.com>
# Created on 12/5/2017
---
- hosts: hostgroup
  remote_user: "{{ user }}"
  become: no
  gather_facts: no
  tasks:
    - name: rsync 'local' directory
      synchronize:
        src=local
        dest=/tmp 
        delete=no

    - name: start fio
      shell: ./start.py -c config-sample.yaml fio
      args:
        chdir: /tmp/local/
      environment: "{{ env }}"
      async: 2592000		# 60*60*24*30 – 1 month
      register: start_fio

    - debug: var=start_fio    
