{{- if .Values.ceph.enabled.exporter }}
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-exporter
  labels:
    version: {{ .Chart.Version }}
    app: ceph
    daemon: exporter
    release: {{ .Release.Name }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - port: {{ .Values.service.exporter.port }}
    protocol: TCP
    targetPort: {{ .Values.service.exporter.port }}
  selector:
    app: ceph
    daemon: exporter
    release: {{ .Release.Name }}
  clusterIP: None
{{ end }}
