#!/bin/bash
# Author: Hee Won Lee <knowpd@research.att.com>
# Created on 10/28/2016

sudo apt-get update
sudo apt-get install -y curl
curl -fsSL https://get.docker.com/ | sh
sudo usermod -aG docker kubearb

