#!/bin/bash
# Author: Hee Won Lee <knowpd@research.att.com>
# Created on 9/12/2017
# src: https://kubernetes.io/docs/setup/independent/install-kubeadm/

set -x

### Install kubelet & kubetadm
sudo apt-get update && sudo apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo sh -c 'cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF'
sudo apt-get update
sudo apt-get install -y --allow-unauthenticated kubelet kubeadm
