#!/bin/bash
# Author: Hee Won Lee <knowpd@research.att.com>
# Created on 9/19/2017
# src: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm
set -x

### From the output of "kubeadm init --pod-network-cidr=192.168.0.0/16"
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

### src: https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
kubectl apply -f http://docs.projectcalico.org/v2.4/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml

### Let's schedule pods on the master node
kubectl taint nodes --all node-role.kubernetes.io/master-
