{{- if .Capabilities.APIVersions.Has "batch/v1"}}
apiVersion: batch/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Job
metadata:
  labels:
    version: {{ .Chart.Version }}
    app: ceph
    release: {{ .Release.Name }}
    daemon: secret-generator
  name: ceph-secret-generator
spec:
  template:
    metadata:
      labels:
        version: {{ .Chart.Version }}
        app: ceph
        release: {{ .Release.Name }}
        daemon: secret-generator
      name: ceph-secret-generator
    spec:
      serviceAccount: default
      restartPolicy: OnFailure
      containers:
        - name: main
          image: {{ .Values.images.ceph_init }}
          imagePullPolicy: {{ .Values.image_policy.pull }}
          env:
            - name: CEPH_GEN_DIR
              value: /opt/ceph
            - name: CEPH_TEMPLATES_DIR
              value: /opt/ceph/templates
          command:
            - bash
            - /opt/ceph/ceph-keys.sh
          volumeMounts:
            - name: ceph-key-gen
              mountPath: /opt/ceph/ceph-keys.sh
              subPath: ceph-keys.sh
              readOnly: true
            - name: ceph-key-gen
              mountPath: /opt/ceph/ceph-key.py
              subPath: ceph-key.py
              readOnly: true
            - name: ceph-key-gen
              mountPath: /opt/ceph/templates/admin.keyring
              subPath: admin.keyring
              readOnly: true
            - name: ceph-key-gen
              mountPath: /opt/ceph/templates/mon.keyring
              subPath: mon.keyring
              readOnly: true
            - name: ceph-key-gen
              mountPath: /opt/ceph/templates/bootstrap.keyring.mds
              subPath: bootstrap.keyring.mds
              readOnly: true
            - name: ceph-key-gen
              mountPath: /opt/ceph/templates/bootstrap.keyring.rgw
              subPath: bootstrap.keyring.rgw
              readOnly: true
            - name: ceph-key-gen
              mountPath: /opt/ceph/templates/bootstrap.keyring.osd
              subPath: bootstrap.keyring.osd
              readOnly: true
            - name: ceph-key-gen                                        # HLEE
              mountPath: /opt/ceph/templates/bootstrap.keyring.rbd      # HLEE
              subPath: bootstrap.keyring.rbd                            # HLEE
              readOnly: true                                            # HLEE
            - name: kube-config                 		                # HLEE
              mountPath: /root/.kube/config		                # HLEE
              subPath: config                                           # HLEE
              readOnly: true                                            # HLEE
      volumes:
        - name: ceph-key-gen
          configMap:
            name: ceph-key-gen
            items:
              - key: ceph-key.py
                path: ceph-key.py
              - key: ceph-keys.sh
                path: ceph-keys.sh
              - key: template.admin.keyring
                path: admin.keyring
              - key: template.mon.keyring
                path: mon.keyring
              - key: template.bootstrap.keyring.mds
                path: bootstrap.keyring.mds
              - key: template.bootstrap.keyring.rgw
                path: bootstrap.keyring.rgw
              - key: template.bootstrap.keyring.osd
                path: bootstrap.keyring.osd
              - key: template.bootstrap.keyring.rbd                     # HLEE
                path: bootstrap.keyring.rbd                             # HLEE
        - name: kube-config				                # HLEE
          secret:					                # HLEE
            secretName: kube-config			                # HLEE
