# Author: Hee Won Lee <knowpd@research.att.com>
# Created on 12/5/2017
---
- hosts: hostgroup
  remote_user: "{{ user }}"
  become: yes
  gather_facts: no
  tasks:
    - name: "apt-get update && apt-get install fio"
      apt:
        name: fio
        update_cache: yes

    - name: "apt-get install bc"
      apt:
        name: bc
        update_cache: no
      register: debugging

    - name: "apt-get install python-pip"
      apt:
        name: python-pip
        update_cache: no

    - name: "pip install pyaml"
      command: pip install pyaml
