# Configuration
influxdb:
  enabled: true
  env: 
    ip: 10.1.2.3     # (influxdb) IP or domain name
    port: 8086       # (influxdb) Port
    dbname: yourdb   # (influxdb) Database name (which should be created beforehand)
    user: yourid     # (influxdb) User ID
    password: yourpw # (influxdb) Password
fio:
  enabled: true
  env:
    runtime: 300                    # FIO runtime (unit: sec)
    direct: 1                       # 1: Direct IO, 2: Buffered IO
    size: 400G                      # io size
    devlist: "sdb sdc"              # block list
    randbslist: "4k 8k 32k"         # random block size list (optional)
    seqbslist: "128k 1024k 4096k"   # sequential block size list (optional)
    readratiolist: "0 30 50 70 100" # read/write ratio: e.g., 30 means read 30% and write 70%
    iodepthlist: "1 8 16 32 64"     # io depth list
    numjobslist: "1 8 16 32"        # number of jobs list
cosbench:
  enabled: false
  env:
    var1: TBD
    var2: TBD
