# Configuration
influxdb:
  enabled: true
  env:
    ip: 10.1.2.3
    port: 8086
    dbname: yourdb      # note: create a database in InfluxDB server
    user: yourid
    password: yourpw
fio:
  enabled: true
  env:
    runtime: 300                  # unit: sec.
    direct: 1
    size: 400G
    devlist: "sdb"
    randbslist: "4k 8k 32k"
    seqbslist: "128k 1024k 4096k"
    readratiolist: "0 30 50 70 100"
    iodepthlist: "1 8 16 32 64"
    numjobslist: "1 8 16 32"
cosbench:
  enabled: false
  env:
    var1: tba
    var2: tba
