---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: ceph-osd-{{ .Values.ceph.osd.node_label }}-{{ .Values.ceph.osd.osd_device}}
  labels:
    version: {{ .Chart.Version }}
    app: ceph
    daemon: osd
    release: {{ .Release.Name }}
spec:
  template:
    metadata:
      labels:
        version: {{ .Chart.Version }}
        app: ceph
        daemon: osd
        release: {{ .Release.Name }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.ceph.osd.node_label }}	# HLEE
        #{{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}	# HLEE: commented out
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet                        	# HLEE
      containers:
        - name: main
          image: {{ .Values.images.daemon }}
          imagePullPolicy: {{ .Values.image_policy.pull }}
          volumeMounts:
            - name: devices
              mountPath: /dev
              readOnly: false
            #- name: ceph
            #  mountPath: /var/lib/ceph
            #  readOnly: false
            #- name: osd-directory
            #  mountPath: /var/lib/ceph/osd
            #  readOnly: false
            - name: ceph-conf
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
              readOnly: true
            - name: ceph-client-admin-keyring
              mountPath: /etc/ceph/ceph.client.admin.keyring
              subPath: ceph.client.admin.keyring
              readOnly: true
            - name: ceph-mon-keyring
              mountPath: /etc/ceph/ceph.mon.keyring
              subPath: ceph.mon.keyring
              readOnly: true
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd/ceph.keyring
              subPath: ceph.keyring
              readOnly: false
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds/ceph.keyring
              subPath: ceph.keyring
              readOnly: false
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw/ceph.keyring
              subPath: ceph.keyring
              readOnly: false
            - name: ceph-bootstrap-rbd-keyring                          # HLEE
              mountPath: /var/lib/ceph/bootstrap-rbd/ceph.keyring       # HLEE
              subPath: ceph.keyring                                     # HLEE
              readOnly: false                                           # HLEE
          securityContext:
            privileged: true
          env:
            - name: CEPH_DAEMON
              value: osd      						# HLEE: was osd_directory
            - name: OSD_TYPE                                            # HLEE
              value: {{ .Values.ceph.osd.osd_type }}                    # HLEE
            - name: OSD_DEVICE                                          # HLEE
              value: /dev/{{ .Values.ceph.osd.osd_device }}             # HLEE
            - name: OSD_FORCE_ZAP                                       # HLEE
              value: {{ .Values.ceph.osd.osd_force_zap | quote }}       # HLEE
            - name: OSD_BLUESTORE                                       # HLEE
              value: {{ .Values.ceph.osd.osd_bluestore | quote }}       # HLEE
            - name: OSD_FILESTORE                                       # HLEE
              value: {{ .Values.ceph.osd.osd_filestore | quote }}       # HLEE
          {{- if .Values.ceph.osd.osd_journal }}                        # HLEE 
            - name: OSD_JOURNAL                                         # HLEE
              value: {{ .Values.ceph.osd.osd_journal }}                 # HLEE
          {{- end }}                                                    # HLEE
            - name: KV_TYPE
              value: k8s
            - name: CLUSTER
              value: {{ .Values.ceph.cluster }}
            - name: CEPH_GET_ADMIN_KEY
              value: "1"
          {{- if .Values.debug_level }}
            - name: DEBUG
              value: {{ .Values.debug_level }}
          {{- end }}
          #livenessProbe:
          #    tcpSocket:
          #      port: 6800
          #    initialDelaySeconds: 60
          #    timeoutSeconds: 5
          #readinessProbe:
          #    tcpSocket:
          #      port: 6800
          #    timeoutSeconds: 5
          resources:
            requests:
              memory: {{ .Values.resources.osd.requests.memory | quote }}
              cpu: {{ .Values.resources.osd.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.osd.limits.memory | quote }}
              cpu: {{ .Values.resources.osd.limits.cpu | quote }}
      volumes:
        - name: devices
          hostPath:
            path: /dev
        #- name: ceph
        #  # emptyDir: {}
        #  hostPath:
        #    path: {{ .Values.ceph.storage.var_directory }}
        #- name: osd-directory
        #  # emptyDir: {}
        #  hostPath:
        #    path: {{ .Values.ceph.storage.osd_directory }}
        - name: ceph-conf
          configMap:
            name: ceph-conf
        - name: ceph-client-admin-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.admin }}
        - name: ceph-mon-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.mon }}
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.osd }}
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.mds }}
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: {{ .Values.secrets.keyrings.rgw }}
        - name: ceph-bootstrap-rbd-keyring                              # HLEE
          secret:                                                       # HLEE
            secretName: {{ .Values.secrets.keyrings.rbd }}              # HLEE
