{{- if .Values.ceph.enabled.rgw }}
---
apiVersion: v1
kind: Service
metadata:
  name: ceph-rgw
  labels:
    version: {{ .Chart.Version }}
    app: ceph
    daemon: rgw
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.service.rgw.port }}
    protocol: TCP
    targetPort: {{ .Values.service.rgw.port }}
  selector:
    app: ceph
    daemon: rgw
    release: {{ .Release.Name }}
{{ end }}
