apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ubnt16-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ubnt16
      namespace: default
    spec:
      #hostNetwork: true 
      #dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: ubnt16
        image: docker.io/knowpd/ceph:kubectl-ubuntu-16.04
        imagePullPolicy: Always
        args:
          - /bin/bash
        stdin: true
        tty: true
