apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deploy-sample
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deploy-sample
      namespace: default
    spec:
      #hostNetwork: true 
      #dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: deploy-sample
          image: docker.io/knowpd/ceph:kubectl-ubuntu-16.04
          imagePullPolicy: Always
          args:
            - /bin/bash
          stdin: true
          tty: true
          volumeMounts:
            - name: vol-sample
              mountPath: /mnt/myvol
      volumes:
        - name: vol-sample
          persistentVolumeClaim:
            claimName: pvc-sample
