---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sample
  annotations:
    volume.beta.kubernetes.io/storage-class: general
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 20Gi
